// reactjs/src/containers/App/App.js
import React, { Component } from 'react';

import { connect } from 'react-redux';

import youtube from 'lib/youtube';

import Search from 'components/Search/Search';
import VideoList from 'components/Videos/VideoList/VideoList';

class App extends Component {
	constructor(props) {
		super(props);

		youtube.createPlayer();
	}

  render() {
    return (
      <div className="app">
				<header className="header">
					<Search />
				</header>

				<main>
				<div className="app__player">
					<div id="yt-player"></div>
      	</div>
      	<div className="app__video-list">
					<VideoList videos={this.props.videos} />
  	    </div>

				</main>
        <footer></footer>
      </div>
    );
  }
}

const mapStateToProps = state => ({
	videos: state.youtube.videos,
})

export default connect(mapStateToProps, null)(App);

// vuejs/src/App.vue
<template>
  <div id="app">
    <header>
      <search></search>
    </header>

    <main>
      <div class="app__player">
        <player class="app__player"></player>
      </div>
      <div class="app__video-list">
        <video-list></video-list>
      </div>
    </main>

    <footer></footer>
  </div>
</template>

<script>

import Player from './components/Player';
import Search from './components/Search';
import VideoList from './components/Video-List';

export default {
  name: 'app',
  components: {
    search: Search,
    videoList: VideoList,
    player: Player,
  },
};
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}
</style>
