// reactjs/src/components/Videos/VideoList/VideoList.js
import React, { Component } from 'react';

import VideoItem from 'components/Videos/VideoItem/VideoItem';

class VideoList extends Component {
	
	render() {
		return (
			<ul className="video-list">
				{ 
					this.props.videos.map((video) => { 
					return (
						<li key={video.id.videoId || video.id.channelId}>
							<VideoItem video={video} /> 
						</li>
					)
				})
				}
			</ul>
		);
	}
}

export default VideoList;

// vuejs/src/components/Video-List.vue
<template>
  <ul class="video-list">
    <li v-for="video in videos" :key="video.id.videoId">
      <video-item :item="video"></video-item>
    </li>
  </ul>
</template>

<script>
import { mapGetters } from 'vuex';

import VideoItem from './Video-Item';

export default {
  name: 'video-list',
  components: {
    videoItem: VideoItem,
  },
  computed: {
    ...mapGetters([
      'videos',
    ]),
  },
};
</script>

<style>

</style>
